{% set name = "lalburst" %}
{% set version = "1.6.2" %}

# dependencies
{% set lal_version = "7.2.2" %}
{% set lalmetaio_version = "3.0.0" %}
{% set lalsimulation_version = "4.0.0" %}
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: 0c9c467e13bd98a4fc808b303f6da9e1b0efb256a5d3f654c15a80bad109402e

build:
  error_overdepending: true
  error_overlinking: true
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - help2man >=1.37
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - gsl
    - liblal >={{ lal_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - liblalsimulation >={{ lalsimulation_version }}
    - metaio

outputs:
  - name: liblalburst
    script: install-lib.sh
    build:
      run_exports:
        - {{ pin_subpackage("liblalburst", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - swig >={{ swig_version }}
      host:
        - gsl
        - liblal >={{ lal_version }}
        - liblalmetaio >={{ lalmetaio_version }}
        - liblalsimulation >={{ lalsimulation_version }}
        - metaio
      run:
        - gsl
        - liblal >={{ lal_version }}
        - liblalmetaio >={{ lalmetaio_version }}
        - liblalsimulation >={{ lalsimulation_version }}
        - metaio
      run_constrained:
        - lalburst >=1.5.7
        - python-lalburst >=1.5.7
    test:
      requires:
        - pkg-config
      commands:
        # check library
        - test -f ${PREFIX}/lib/liblalburst${SHLIB_EXT}  # [unix]
        # check pkg-config
        - pkg-config --print-errors --exact-version "${PKG_VERSION}" lalburst
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Burst Library shared object libraries
      description: |
        The LSC Algorithm Burst Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Burst library.

  - name: python-lalburst
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - numpy
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
        # extras for cross compiling
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
      host:
        - gsl
        - {{ pin_subpackage('liblalburst', exact=True) }}
        - lscsoft-glue
        - numpy
        - python
        - python-lal >={{ lal_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - scipy
        - tqdm
      run:
        - gsl
        - {{ pin_subpackage('liblalburst', exact=True) }}
        - ligo-segments
        - lscsoft-glue
        - matplotlib-base
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - python-ligo-lw >=1.7.0
        - scipy
        - tqdm
    test:
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        - python -m pytest -rs -v test/python
      imports:
        - lalburst
        - lalburst.SimBurstUtils
        - lalburst.SnglBurstUtils
        - lalburst.binjfind
        - lalburst.bucluster
        - lalburst.burca
        - lalburst.burca_tailor
        - lalburst.cafe
        - lalburst.calc_likelihood
        - lalburst.cs_gamma
        - lalburst.date
        - lalburst.offsetvector
        - lalburst.packing
        - lalburst.power
        - lalburst.snglcluster
        - lalburst.snglcoinc
        - lalburst.stringutils
        - lalburst.timeslides
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Burst Library Python bindings
      description: |
        The LSC Algorithm Burst Library for gravitational wave data analysis.
        This package contains the Python bindings of the LALBurst C libraries
        and additional Python modules.

        Note: this package only provides the importable Python libraries.
        All command-line interfaces, scripts, and executables are
        part of the `lalburst` package.

  - name: lalburst
    script: install-bin.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - sed
      host:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalburst', exact=True) }}
        - python
      run:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalburst', exact=True) }}
        - pillow
        - python
        - {{ pin_subpackage('python-lalburst', exact=True) }}
    test:
      commands:
        - lalburst_cluster --help
        - lalburst_coinc --help
        - lalburst_cut --help
        - lalburst_injfind --help
        - lalburst_inj_pic --help
        - lalburst_plot_tisi --help
        - lalburst_power_calc_likelihood --help
        - lalburst_power_final --help
        - lalburst_power_meas_likelihood --help
        - lalburst_power_plot_binj --help
        - lalburst_power_plot_binjtf --help
        - lalburst_version --verbose
      imports:
        - lalburst
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Burst Library
      description: |
        The LSC Algorithm Burst Library for gravitational wave data analysis.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Burst Library
  description: |
    The LSC Algorithm Burst Library for gravitational wave data analysis.

extra:
  feedstock-name: lalburst
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
