{% set name = "lalburst" %}
{% set version = "1.5.5" %}
{% set sha256 = "8784e9aefd780ae130a1f99c7d2c7f678970ab72fc096eb8636e1c04089e813f" %}

# dependencies
{% set lal_version = "7.0.0" %}
{% set lalmetaio_version = "1.6.0" %}
{% set lalsimulation_version = "2.1.0" %}
{% set swig_version = "3.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - gsl
    - lal >={{ lal_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - metaio
  run:
    - gsl
    - lal >={{ lal_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - metaio

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - lalburst_version --verbose
    - test "$(pkg-config --modversion ${PKG_NAME})" == "${PKG_VERSION}"  # [unix]

outputs:
  - name: lalburst
    build:
      run_exports:
        - {{ pin_subpackage("lalburst", max_pin="x.x") }}

  - name: python-lalburst
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('lalburst', exact=True) }}
        - numpy
        - python
      run:
        - gsl
        - lal >={{ lal_version }}
        - lalmetaio  # [linux]
        - lalsimulation  # [linux]
        - {{ pin_subpackage('lalburst', exact=True) }}
        - ligo-segments
        - lscsoft-glue
        - matplotlib-base
        - metaio  # [linux]
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - python-ligo-lw
        - scipy
    test:
      imports:
        - lalburst
        - lalburst.SimBurstUtils
        - lalburst.SnglBurstUtils
        - lalburst.binjfind
        - lalburst.bucluster
        - lalburst.burca
        - lalburst.burca_tailor
        - lalburst.cafe
        - lalburst.calc_likelihood
        - lalburst.cs_gamma
        - lalburst.date
        - lalburst.offsetvector
        - lalburst.packing
        - lalburst.snglcluster
        - lalburst.snglcoinc
        - lalburst.stringutils
        - lalburst.timeslides
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        - pushd test/python; python -m pytest -v; popd
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Burst Library
      description: |
        The LSC Algorithm Burst Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Burst Library
  description: |
    The LSC Algorithm Burst Library for gravitational wave data analysis.
    This package contains the shared-object libraries needed to run
    applications that use the LAL Burst library.  If you want to install
    the Python bindings, please install the associated python-lalburst
    package.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
