{% set name = "lalburst" %}
{% set version = "1.5.2" %}
{% set sha256 = "f0c9077a544274aef05a4a88839a50bc737de141b4fb340e925d37db82ddcb47" %}

# dependencies
{% set lal_version = "6.20.0" %}
{% set lalmetaio_version = "1.5.0" %}
{% set lalsimulation_version = "1.9.0" %}
{% set swig_version = "3.0.7" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - gsl
    - lal >={{ lal_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - metaio
  run:
    - gsl
    - lal >={{ lal_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - metaio

test:
  commands:
    - lalburst_version --verbose
    - conda inspect linkages -p ${PREFIX} ${PKG_NAME}  # [not win]
    - conda inspect objects -p ${PREFIX} ${PKG_NAME}  # [osx]

outputs:
  - name: lalburst
    build:
      run_exports:
        - {{ pin_subpackage("lalburst", max_pin="x.x") }}

  - name: python-lalburst
    script: install-python.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('lalburst', exact=True) }}
        - lscsoft-glue
        - numpy
        - python
        - python-lal >={{ lal_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - scipy
      run:
        - gsl
        - lal >={{ lal_version }}
        - {{ pin_subpackage('lalburst', exact=True) }}
        - ligo-segments
        - lscsoft-glue
        - matplotlib
        - metaio
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - python-ligo-lw
        - scipy
    test:
      imports:
        - lalburst
        - lalburst.SimBurstUtils
        - lalburst.SnglBurstUtils
        - lalburst.binjfind
        - lalburst.bucluster
        - lalburst.burca
        - lalburst.burca_tailor
        - lalburst.cafe
        - lalburst.calc_likelihood
        - lalburst.cs_gamma
        - lalburst.date
        - lalburst.packing
        - lalburst.snglcluster
        - lalburst.snglcoinc
        - lalburst.timeslides
      commands:
        - conda inspect linkages -p ${PREFIX} ${PKG_NAME}  # [not win]
        - conda inspect objects -p ${PREFIX} ${PKG_NAME}  # [osx]
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Burst Library
      description: |
        The LSC Algorithm Burst Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Burst Library
  description: |
    The LSC Algorithm Burst Library for gravitational wave data analysis.
    This package contains the shared-object libraries needed to run
    applications that use the LAL Burst library.  If you want to install
    the Python bindings, please install the associated python-lalburst
    package.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
