{% set name = "lalburst" %}
{% set version = "1.5.0" %}
{% set sha256 = "2918c61c8c767bfa1fc2d439e9b7ca15e0e7a186ec045a6b563f9dcb6c1a1ca2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    # patch relative imports of lalburst.git_version
    - python3-git_version.patch

build:
  number: 1001
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - swig >=3.0.7
  host:
    - gsl
    - metaio
    - lal >=6.19.0
    - lalmetaio >=1.4.0
    - lalsimulation >=1.8.0

outputs:
  - name: lalburst
    script: install-c.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - pkg-config
        - make
        - swig >=3.0.7
      host:
        - gsl
        - metaio
        - lal >=6.19.0
        - lalmetaio >=1.4.0
        - lalsimulation >=1.8.0
      run:
        - gsl
        - metaio
        - lal >=6.19.0
        - lalmetaio >=1.4.0
        - lalsimulation >=1.8.0
    test:
      commands:
        - lalburst_version --verbose
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Burst Library
      description: |
        The LSC Algorithm Burst Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Burst library.

  - name: python-lalburst
    script: install-python.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - pkg-config
        - make
        - swig >=3.0.7
      host:
        - {{ pin_subpackage('lalburst', exact=True) }}
        - python
        - numpy
        - python-lal >=6.19.0
        - python-lalmetaio >=1.4.0
        - python-lalsimulation >=1.8.0
        - lscsoft-glue
        - scipy
      run:
        - {{ pin_subpackage('lalburst', exact=True) }}
        - python
        - {{ pin_compatible('numpy') }}
        - python-lal >=6.19.0
        - python-lalmetaio >=1.4.0
        - python-lalsimulation >=1.8.0
        - matplotlib
        - lscsoft-glue
        - scipy
    test:
      imports:
        - lalburst
        - lalburst.SimBurstUtils
        - lalburst.SnglBurstUtils
        - lalburst.binjfind
        - lalburst.bucluster
        - lalburst.burca
        - lalburst.burca_tailor
        - lalburst.cafe
        - lalburst.calc_likelihood
        - lalburst.cs_gamma
        - lalburst.date
        - lalburst.packing
        - lalburst.snglcluster
        - lalburst.snglcoinc
        - lalburst.timeslides
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalburst/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Burst Library
      description: |
        The LSC Algorithm Burst Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/Computing/DASWG/LALSuite
  license: GPLv3
  license_family: GPL
  summary: LSC Algorithm Burst Library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
