travis:
  secure:
    BINSTAR_TOKEN: TnIPgZMGzwGInEiDqnvXthU5EcEUrmS99lLs8xsqEYAjJ/EnKads8Tcap6m2Nlib8LSvEpkq6bfRmmio6AnX/WoA6V4tgbxrxk8x/Uoq5k5yU/677ObMzuBfNcTCTbj3aZTKTmRfdaInpzf5GT60RYvuHj2sZeJiA5dAH2C48mNcXPBFI83Bu4yS/eoBqITMtHO5Ji2Ki5aGVQ6g+0jyJYCXTQvP4W3JMB6AmETUimYjrrmjhVaQJ6hMSg22nFWlNK3KkscV/f9GcZVcfOLQcKb7OVB3YXa1VLa2oYuQqQwxRMky9AxJIxetuVdll7zc0vQOPJVgUhgByHpsxndLZ6INm0lXY14Q9fbHcLDX7kgJnYVqHc8U2E1FYQyK/UKv6z9c8hRW3K18EZYXZriaTU5AF2J4dwgLHdx/1vn3JP4et4nZJG5CDdbTSL4TdDA+7cFUqwKfQkhwvri/Gww10hhZB18WynzGztNbbBaf5DBS5E1D6zIddDLynXiU4ohbBLOVZXuYJ9sEbdR8JvZ0fm9+EC4gr4UKtPNNPL9L5QtDrIg2J/3AYs/NXvq2lA0HTmzonEMPBzuP2oTj9A2zsxZjP+q2hEwFf2vx1jvA8qOEyR5Xc+zJDywFMLjKcCYbn36ZmvRXcy5svdMnbuwSLv0v3zOFAXW8PD0svUl1OyM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
